version: '3.8'
services:
  video-matting:
    build: .
    restart: unless-stopped
    shm_size: 8g
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
